run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - gofmt
    - goimports
    - misspell
    - lll

linters-settings:
  gofmt:
    simplify: true
  lll:
    line-length: 120
  misspell:
    locale: "US"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gofmt
        - goimports